# Generated by Django 5.0.1 on 2024-01-28 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tutors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('qualification', models.CharField(max_length=100)),
                ('desc', models.CharField(max_length=1000)),
                ('linkdin', models.CharField(blank=True, max_length=500, null=True)),
                ('Xaccount', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
